// <auto-generated />
namespace trytest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RenameUserAge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameUserAge));
        
        string IMigrationMetadata.Id
        {
            get { return "201505311244314_RenameUserAge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
